
development:
  adapter: postgresql
  encoding: unicode
  database: clocks_development
  pool: 5
  host: localhost
  username: janesternbach
  password:


test:
  adapter: postgresql
  encoding: unicode
  database: clocks_test
  pool: 5
  host: localhost
  username: janesternbach
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: clocks_production
  pool: 5
  host: localhost
  username: janesternbach
  password:
