Book.delete_all
Author.delete_all

Author.create(:name =>"Jeffrey Eugenides", :age =>52, :awards =>"Pulitzer Prize for Fiction", :image =>"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDAMavUHWYN9j1ekgF5EfnnSmhLqe3mR_aZ5jbiey7j64dW4vy0iq-1sPZ")
Author.create(:name =>"J.K. Rowling", :age =>47, :awards =>"Nestle Smarties Book Prize", :image =>"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTP-j01r3Kn-DIt8568sJV5kxeno0keQzCjjK5KIZ2kRENjFPiW")
Author.create(:name =>"Mark Helprin", :age =>65, :awards =>"Helmerich Award", :image =>"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSz9DT5GAlwR7OpXdkzfM1u5xIW_QlA6Vt7_L7fK_t7Un0o7C5t")
Author.create(:name =>"James Frey", :age =>43, :awards =>"", :image =>"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-hWKgS9y2hvU3RgEx2e8GvyJA2RxVNnKhqIh9tPsMDSm29SYdzhyAZsX9")
Author.create(:name =>"Jonathan Safran Foer", :age =>35, :awards =>"Guardian First Book Award", :image =>"https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRJPTDYOIUTcHCxwXh04tNkuym0ILD8GntGHwzPm8ML0_7NPbYDcg")
Author.create(:name =>"Charlaine Harris", :age =>61, :awards =>"Agatha Award for Best Novel", :image =>"http://www.charlaineharris.com/photos/ParanormalPhoto_homepage.jpg")
Author.create(:name =>"John Steinnbeck", :age =>nil, :awards =>"Nobel Prize in Literature, Pulitzer Prize for Fiction, Pulitzer Prize for Novel", :image =>"http://www.biography.com/imported/images/Biography/Images/Profiles/S/John-Steinbeck-9493358-1-402.jpg")
Author.create(:name =>"F. Scott Fitzgerald", :age =>nil, :awards =>"", :image =>"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_8CsvmVqYwshRMEUa2t3GMrJH9F9etUFsOz49-782JAW9h5DY")

Book.create(:title => "Harry Potter and the Sorcerer's Stone", :released => "1997-6-30", :publisher => "Scholastic", :genre => "Young Adult Fantasy", :cover => "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRaWr_N_BE5_0TiXMGdvbVsgsukpf0qSp7E_j8zyn9NaO5N-HexA")
Book.create(:title => "Harry Potter and the Chamber of Secrets", :released => "1998-7-2", :publisher => "Scholastic", :genre => "Young Adult Fantasy", :cover => "")
Book.create(:title => "Harry Potter and the Prisoner of Azkaban", :released => "1998-7-8", :publisher => "Scholastic", :genre => "Young Adult Fantasy", :cover => "")
Book.create(:title => "Harry Potter and the Goblet of Fire", :released => "2000-7-8", :publisher => "Scholastic", :genre => "Young Adult Fantasy", :cover => "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMPglIGprN4viRGLcYIriztNAa793zg6VbddC6lKhmqJUJGG16JQ")
Book.create(:title => "Harry Potter and the Order of the Phoenix", :released => "2003-6-21", :publisher => "Scholastic", :genre => "Young Adult Fantasy", :cover => "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSn17BMVOt4aZasE1NdpiShP1-PqBjQQ1l2XteTsX8arEFe45ZA")
Book.create(:title => "Harry Potter and the Half-Blood Prince", :released => "2005-7-16", :publisher => "Scholastic", :genre => "Young Adult Fantasy", :cover => "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQDFS8_I41QgbVMsQKCIEkT7qnBcQZaNNa-1fL4g-qFQXmuzhsj")
Book.create(:title => "Harry Potter and the Deathly Hallows", :released => "2007-7-21", :publisher => "Scholastic", :genre => "Young Adult Fantasy", :cover => "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyKV0-WVQFOnMby-dVcKOnSaToYCpoRna7HFKvvOKJOOY_1TGG-w")
Book.create(:title => "Middlesex", :released => "2002-10-7", :publisher => "Farrar, Straus and Giroux", :genre => "Fiction", :cover => "http://z.about.com/d/bestsellers/1/0/c/B/-/-/middlesex.JPG")
Book.create(:title => "Winter's Tale", :released => "1983-10-20", :publisher => "Harcourt, Brace, Jovanovich", :genre => "Magical Realism", :cover => "http://upload.wikimedia.org/wikipedia/en/thumb/5/51/MarkHelprin_WintersTale.jpg/200px-MarkHelprin_WintersTale.jpg")
Book.create(:title => "A Million Little Pieces", :released => "2003-4-15", :publisher => "Random House", :genre => "Fiction", :cover => "http://upload.wikimedia.org/wikipedia/en/3/37/A_Million_Little_Pieces.jpg")
Book.create(:title => "My Friend Leonard", :released => "2005-6-16", :publisher => "Random House", :genre => "Fiction", :cover => "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXQsG7h83GtLQ7Zp7ymJe-achpOSYQvFLKOgq5zXZTICNnrccmKQ")
Book.create(:title => "Bright and Shiny Morning", :released => "2008-5-13", :publisher => "Random House", :genre => "Fiction", :cover => "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcT15VlRzu4QZrYrrGR_GnZbAZNzzoc2NUu4eF2MQsuXnZyVlBNf")
Book.create(:title => "Everything is Illuminated", :released => "", :publisher => "", :genre => "", :cover => "http://contentcafe2c.btol.com/ContentCafe/Jacket.aspx?UserID=EBSCHEMEKETA&Password=CHEMEKETA&Return=T&Type=L&Value=9780618173877")
Book.create(:title => "Extremely Loud and Incredibly Close", :released => "", :publisher => "", :genre => "", :cover => "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSfHyw1he58YFQ2kvK6g3FuC0nWBoIgIEIfarkiRSTl7c3oDAIEw")
Book.create(:title => "Dead Until Dark: A Sookie Stackhouse Novel", :released => "", :publisher => "Penguin Publishing", :genre => "Fantasy", :cover => "http://2.bp.blogspot.com/-XWOh1fCvjuM/UMIK7xZbVKI/AAAAAAAADnM/JmAlykFZqmg/s1600/dead-until-dark.jpg")
Book.create(:title => "Living Dead in Dallas: A Sookie Stackhouse Novel", :released => "", :publisher => "Penguin Publishing", :genre => "Fantasy", :cover => "http://4.bp.blogspot.com/-F_1oJrC0cDA/T34YvFg7qZI/AAAAAAAAArk/G6KJHKkhnMs/s640/living-dead-in-dallas.jpg")
Book.create(:title => "Club Dead: A Sookie Stackhouse Novel", :released => "", :publisher => "Penguin Publishing", :genre => "Fantasy", :cover => "http://www.earlyword.com/wp-content/uploads/2008/12/livingdead.jpg")
Book.create(:title => "Dead to the World: A Sookie Stackhouse Novel", :released => "", :publisher => "Penguin Publishing", :genre => "Fantasy", :cover => "http://thtswhatsheread.files.wordpress.com/2012/07/cover-deadtotheworld.jpg")
Book.create(:title => "East of Eden", :released => "", :publisher => "", :genre => "", :cover => "http://blogs.publishersweekly.com/blogs/PWxyz/wp-content/uploads/2011/11/eden2.jpg")
Book.create(:title => "Of Mice and Men", :released => "", :publisher => "", :genre => "", :cover => "http://www.mykidthinksthat.com/wp-content/uploads/2012/07/of-mice-and-men.jpg")
Book.create(:title => "Grapes of Wrath", :released => "", :publisher => "", :genre => "", :cover => "http://www.writtenword.com/wp-content/uploads/2012/04/Grapes-of-Wrath.jpg")
Book.create(:title => "The Great Gatsby", :released => "", :publisher => "", :genre => "", :cover => "http://collider.com/wp-content/uploads/THE-GREAT-GATSBY-400x600.jpg")
Book.create(:title => "This Side of Paradise", :released => "", :publisher => "", :genre => "", :cover => "http://literarytransgressions.files.wordpress.com/2011/07/fitzparadise.jpg")
