development:
  adapter: postgresql
  encoding: unicode
  database: numb3rs_development
  pool: 5
  host: localhost
  username: janesternbach
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: numb3rs_test
  pool: 5
  host: localhost
  username: janesternbach
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: numb3rs_production
  pool: 5
  host: localhost
  username: janesternbach
  password:
